# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeerStyles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint', '0.31.0'
  # Pods for BeerStyles

end
